# Generated by Django 4.0.3 on 2022-03-21 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('brand', models.CharField(default='', max_length=255)),
                ('countryOfOrigin', models.CharField(default='', max_length=255)),
                ('material', models.CharField(default='', max_length=255)),
                ('occasion', models.CharField(default='', max_length=255)),
                ('fasteningType', models.CharField(default='', max_length=255)),
                ('size', models.CharField(default='', max_length=255)),
                ('heelsHeight', models.CharField(default='', max_length=255)),
                ('wideFit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShoesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('description', models.CharField(default='', max_length=255)),
                ('header', models.CharField(default='', max_length=255)),
                ('discount', models.FloatField(default=0)),
                ('isPay', models.BooleanField(default=False)),
                ('shoe', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoes.shoes')),
            ],
        ),
        migrations.CreateModel(
            name='KidShoes',
            fields=[
                ('shoes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shoes.shoes')),
                ('gender', models.CharField(default='', max_length=255)),
                ('recommendedAge', models.FloatField(default=0)),
                ('shoesStyle', models.CharField(default='', max_length=255)),
            ],
            bases=('shoes.shoes',),
        ),
        migrations.CreateModel(
            name='MenShoes',
            fields=[
                ('shoes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shoes.shoes')),
                ('leatherType', models.CharField(default='', max_length=255)),
            ],
            bases=('shoes.shoes',),
        ),
        migrations.CreateModel(
            name='WomanShoes',
            fields=[
                ('shoes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shoes.shoes')),
                ('session', models.CharField(default='', max_length=255)),
            ],
            bases=('shoes.shoes',),
        ),
        migrations.CreateModel(
            name='ShoesItemImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='shoes/')),
                ('shoesItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.shoesitem')),
            ],
        ),
    ]
