# Generated by Django 4.0.3 on 2022-03-21 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(default='', max_length=255)),
                ('batteryCapacity', models.CharField(default='', max_length=255)),
                ('warrantyDuration', models.CharField(default='', max_length=255)),
                ('warrantyType', models.CharField(default='', max_length=255)),
                ('condition', models.CharField(default='', max_length=255)),
                ('screenSize', models.CharField(default='', max_length=255)),
                ('brand', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('description', models.CharField(default='', max_length=255)),
                ('header', models.CharField(default='', max_length=255)),
                ('discount', models.FloatField(default=0)),
                ('isPay', models.BooleanField(default=False)),
                ('electronic', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='electronic.electronic')),
            ],
        ),
        migrations.CreateModel(
            name='laptop',
            fields=[
                ('electronic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='electronic.electronic')),
                ('ram', models.CharField(default='', max_length=255)),
                ('laptopType', models.CharField(default='', max_length=255)),
                ('storageType', models.CharField(default='', max_length=255)),
                ('weight', models.CharField(default='', max_length=255)),
                ('card', models.CharField(default='', max_length=255)),
            ],
            bases=('electronic.electronic',),
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('electronic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='electronic.electronic')),
                ('ram', models.CharField(default='', max_length=255)),
                ('processorType', models.CharField(default='', max_length=255)),
                ('storageCapacity', models.CharField(default='', max_length=255)),
                ('mobileCableType', models.CharField(default='', max_length=255)),
            ],
            bases=('electronic.electronic',),
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('electronic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='electronic.electronic')),
                ('eReader', models.BooleanField(default=False)),
                ('storageCapacity', models.CharField(default='', max_length=255)),
            ],
            bases=('electronic.electronic',),
        ),
        migrations.CreateModel(
            name='ElectronicItemImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='electronic/')),
                ('electronicItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic.electronicitem')),
            ],
        ),
    ]
